version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (*database/sql.DB).Close
        - (*database/sql.Rows).Close
        - fmt.Fprintf
        - fmt.Fprintln
        - (*text/tabwriter.Writer).Flush
        - (*io.PipeWriter).Close
        - (*database/sql.DB).Exec
